silex-skeleton/src/Entity/Product.php
<?php

namespace Entity;

Class Product{
    
    /**
     *
     * @var int
     */
    private $id_product;
    
    /**
     *
     * @var string
     */
    private $product_name;
    
    /**
     *
     * @var string
     */
    private $description;

    /**
     *
     * @var string
     */
    private $photo;
    
    /**
     *
     * @var int
     */
    private $price;
    
    /**
     *
     * @var string
     */
    private $size;
    
    /**
     *
     * @var string
     */
    private $frequency;


// Getter


    public function getIdProduct(){
        return $this->id_product;
    }


    public function getProductName(){
        return $this->product_name;
    }

    public function getDescription(){
        return $this->description;
    }

    public function getPhoto(){
        return $this->photo;
    }

    public function getPrice(){
        return $this->price;
    }
    
    public function getSize(){
        return $this->size;
    }
    
    public function getFrequency(){
        return $this->frequency;
    }

// Setter

    public function setIdProduct($id_product){
        $this->id_product = $id_product;
        return $this;
    }

    public function setProductName($product_name){
        $this->product_name = $product_name;
        return $this;
    }

    public function setDescription($description){
        $this->description = $description;
        return $this;
    }


    public function setPhoto($photo){
        $this->photo = $photo;
        return $this;
    }

    public function setPrice($price){
        $this->price = $price;
        return $this;
    }
    
    public function setSize($size){
        $this->size = $size;
        return $this;
    }
    
    public function setFrequency($frequency){
       $this->frequency = $frequency;
       return $this;
    }
}

silex-skeleton/templates/article_list.html.twig
{% extends "layout.html.twig" %}


{% block content %}

      <link rel="stylesheet" href="{{ asset('css/article_list.css') }}" type="text/css">



   {% autoescape %}
    <section class="introblog">
        <h2 class="actutitle">Les Carnets</h2>
        
        <ul>
            {% for category in categories %}

                <li><a href="{{ path('category', {id: category.idcategory}) }}">{{ category.categoryname }}</a></li>

            {% endfor %}

        </ul>
    </section>
    
    
    
    {#%  include 'categories.html.twig' %#}

    <section  class="containeractu">

        <section class="sectionactu">

            {% for article in articles %}

                <div class="actuarticle">
                    <h3>{{ article.title|raw }}</h3>
                    <aside><small> dans {{ article.category_name|raw }}</small></aside>
                </div>   
                <div class="left">
                    <div class="actuimg" style="background-image: url('{{ asset('img/' ~ article.picture) }}" alt="photo de l'article {{article.title|raw}}')"></div>
                </div>
                
                <div class="actuarticle">

                    <div class="traitprofile"></div>

                        <p class="descriptionourproject">{{ article.short_content|raw }}</p>
                        <div class="btn_plus"><a target="_blank" href="{{path('article', {id: article.id_article})}}"><img src="{{ asset('img/btn_plus.png') }}" alt="bouton en savoir plus"></a></div>
                           
                    <div class="clear"></div>
                </div>

        </section>

    </section>
        
    <section  class="containeractu">

        <section class="sectionactu">

                {% if not loop.last %}

                {%endif%}
        
        </section>
            {% endfor %}


        

    </section>
    {% endautoescape %}    


{% endblock %}
    

silex-skeleton/templates/category.html.twig
{% extends "layout.html.twig" %}


{% block content %}

      <link rel="stylesheet" href="{{ asset('css/article_list.css') }}" type="text/css">
       <link rel="stylesheet" href="{{ asset('css/category.css') }}" type="text/css">



   {#% autoescape %#}
    <section class="introblog">
               
        <h2 class="actutitle">Carnet</h2>
        

        
        <ul>
            {% for category in categories %}

                <li><a href="{{ path('category', {id: category.idcategory}) }}">{{ category.categoryname }}</a></li>

            {% endfor %}

        </ul>
            
                    

    </section>
            
             


    <section  class="containeractu">
        
        <h3>{{ category.categoryname }}</h3>
        
        <section class="sectionactu">

            {% for article in articles %}
                <div class="left">
                    <div class="actuimg" style="background-image: url('{{ asset
                    ('img/' ~ article.picture) }}" alt="photo de l'article {{article.title|raw}}')"></div>
                </div>


                <div class="actuarticle">
                    <h3>{{ article.title|raw }}</h3>
                    <aside><small> dans {{ category.CategoryName|raw }}</small></aside>

                    <div class="traitprofile"></div>

                        <p class="descriptionourproject">{{ article.ShortContent|raw }}</p>
                        <div class="btn_plus"><a target="_blank" href="{{path('article', 
                        {id: article.IdArticle})}}"><img src="{{ asset('img/btn_plus.png') }}" alt="bouton en savoir plus"></a></div>
                           
                    <div class="clear"></div>
                </div>

        </section>

    </section>
        
    <section  class="containeractu">

        <section class="sectionactu">

                {% if not loop.last %}

                {%endif%}
        
        </section>
            {% endfor %}


        

    </section>
     


{% endblock %}
    

silex-skeleton/templates/contact.html.twig
{% extends "layout.html.twig" %}

{% block content %}

    <link rel="stylesheet" href="{{ asset('css/contact2.css') }}" type="text/css">


    
    <section id="contact">
        <article>
            <div>
                <div>
                    <h2>Vous avez une question ?</h2>
                    <p> Ecrivez-nous,  nous vous répondrons personnellement. </p>
                </div>


                
                {%if sent is defined%}
                    <p>Votre message a bien été envoyé. Nous vous répondrons aussi vite que possible.</p>
                {%else%}
                    <form method="post">
                        <select name="choice" id="choice">
                            <option value="null">--Vous êtes:--</option>
                            <option value="entreprise">Une entreprise</option>
                            <option value="particulier">Un particulier</option>
                        </select>

                        <label id="society"> Nom de l'entreprise</label>
                        <input type="text" id="societyName" placeholder="Nom de l'entreprise">

                        <label for="email">Email</label>
                        <input type="text" id="email" name="email" value="" placeholder="Email">

                        <label for="phone">Téléphone</label>
                        <input type="text" id="phone" name="phone" value="" placeholder="Téléphone">

                        <label for="zipcode">Code postal</label>
                        <input type="text" id="zipcode" name="zipcode" value="" placeholder="Code Postal">

                        <label for="message">Votre message</label>
                        <textarea id="message" name="message" value="" placeholder="Votre message"></textarea>

                        <input type="submit" value="Valider">
                    </form>
                {%endif%}
            </div>

        </article>

    </section>

{% endblock %}




    {% block javascripts %}

        {{ parent() }}

            <script src="{{asset('js/contact.js')}}"> </script>

      {% endblock %}

silex-skeleton/templates/gift_card.html.twig
{% extends "layout.html.twig" %}

{% block content %}

  <link rel="stylesheet" href="{{ asset('css/gift_card.css') }}" type="text/css">

    <section id="giftcard">
        <h2>Activez votre carte cadeau Fleurs d'Ici ! </h2>


<section class="cardcontainer">
    <section id="card">
        
        <i class="fa fa-circle-thin" aria-hidden="true"></i>
        <div id="illucard"></div>
            {% if user_manager.isUserConnected %}  

            <form action="" method="post">
                <label for="code">Entrez votre code cadeau</label>
                <input type="text" name="code">
                <input type="submit">
            </form>

                {%if gift is defined %}
                    <p>Votre carte cadeau est bien activée !</p>
                {%endif%}   
                
            {%else%} 

                <p>Pour activer votre carte cadeau, <a href="{{path('login')}}">connectez vous</a> à votre compte Fleurs d'ici !</p>
                <p>Vous n'avez pas encore de compte ? <a href="{{path('register')}}">Inscrivez-vous</a> dès maintenant ! </p>

            {%endif%}

        </section>
    </section>
</section>

{% endblock %}

silex-skeleton/templates/index.html.twig
{% extends "layout.html.twig" %}

{% block stylesheet %}
{{ parent() }}
<link rel="stylesheet" href="{{asset('css/index.css')}}">
{% endblock %}

{% block content %}

    <section id="mainindex">

    {#section header#}

    <section id="sectionhome1">
        <section class="contenuindex">
            <article>
                <h2>Comme si vous les aviez cueillies</h2>
                <div class="traitprofile"></div>
                <p>Les Fleurs d'Ici, première marque de fleurs coupées qui contribue à la protection de la nature et des emplois en France. Des fleurs locales et de saison, en circuit court. </p>
                {#<form method="post" id="choix">
                    <select name="frequency" >
                        <option value="null">FREQUENCE</option>
                        <option value="once_a_month">Une fois par mois</option>
                        <option value="twice_a_month">Deux fois par mois</option>
                    </select>
                    <select name="size">
                        <option value="null">TAILLE DU BOUQUET</option>
                        <option value="moyen">Moyen</option>
                        <option value="gros">Gros</option>
                    </select>
                    <input type="submit" value="Valider">
                </form>#}
                <div class="btn_plus"><a href="{{path('abonnement')}}" id="sabonner"><img src="{{ asset('/web/img/btn_plus.png') }}" alt="bouton s'abonner"></a> <b>La boutique</b> </div>
                           
            </article>

            <!--img src="{{ asset('/web/img/header.png') }}" alt="bouquet"-->
        </section>
    </section>

    {#Section cheminement Pictos#}
    <section id="sectionhome4">
        <section class="contenuindex">
            <h2>Comment ça marche ?</h2>
            <div class="traitprofile"></div>
            
            <article id="refractaire">
                <figure>
                    <img src="/web/img/Picto_2.svg" alt="">
                    <figcaption>Vous vous abonnez en ligne.</figcaption>
                </figure>
            </article>

            <article>
                <figure>
                    <img src="/web/img/Picto_4.svg" alt="">
                    <figcaption>Nous sélectionnons la variété avec le producteur selon la saison.</figcaption>
                </figure>
            </article>

            <article>
                <figure>
                    <img src="/web/img/Picto_3.svg" alt="">
                    <figcaption>Les fleurs sont cueillies la veille de la livraison.</figcaption>
                </figure>
            </article>

            <article>
                <figure>
                    <img src="/web/img/Picto_1.svg" alt="">
                    <figcaption>Les fleurs sont livrées chez vous dans la journée.</figcaption>
                </figure>
            </article>

            <p><a class="box" href="{{path('project')}}#mainproject2"> Pourquoi des fleurs en circuit court ? </a></p>
        </section>
    </section>

{#
    Section notre projet
        <section id="sectionhome2">
            <section class="contenuindex">
                <h2>Le projet</h2>
                <div class="traitprofile"></div>
                <p>Fleurs d'ici est la première marque de fleurs coupées qui permet de contribuer à la protection de la nature et des emplois en France.
                Des fleurs locales et de saison, comme si vous veniez de les cueillir au jardin.</p>

                <article>
                    <img src="{{ asset('img/photo1.png') }}" alt="logo">
                    <h3>Des fleurs authentiques</h3>
                    <p>Roses parfumées, iris, pivoines, lilas : des variétés sélectionnées dans un esprit jardin</p>
                </article>

                <article>
                    <img src="{{ asset('img/photo2.png') }}" alt="logo">
                    <h3>Des fleurs locales</h3>
                    <p>Des fleurs en circuit-court, produites artisanalement, qui préservent l’emploi et l’environnement</p>
                </article>

                <article>
                    <img src="{{ asset('img/photo3.png') }}" alt="logo">
                    <h3>Des fleurs fraîches</h3>
                    <p> Nos producteurs cueillent les plus belles fleurs de saison, à maturité, 24h avant d'être chez vous</p>
                </article>

                <p><a class="box" href="{{path('project')}}">En savoir plus sur notre projet</a></p>
            </section>
        </section>#}


    <section id="sectionhome2" > 
        
        <section class="contenuindex" >

            <article>
                <h2>Un concept innovant</h2>
                <div class="traitprofile"></div>

                <p class="descriptionourproject">Les Fleurs d'Ici c'est la première marque de fleurs coupées qui permet de contribuer à la protection de la nature et des emplois en France.
                Des fleurs locales et de saison, comme si vous veniez de les cueillir au jardin.</p>
            </article>
            
            <img src="/web/img/ban_projet.jpg" alt="photographie de la marchande de fleurs">
        </section>

    </section>




    {# Section producteurs #}
        {#<section id="sectionhome3">
            <section class="contenuindex">
                <article>
                    <h2>Rencontrez nos producteurs</h2>
                    <div class="traitprofile"></div>
                    <p id="line" class="infos">Chez Fleurs d'Ici on a souhaité vous proposer une approche, qui remet la saisonnalité et la proximité au coeur de la démarche.
                    En limitant les intermédiaires, Fleurs d'Ici permet aux petits producteurs horticoles de pratiquer des prix plus justes, et aux consommateurs d'avoir des produits de meilleure qualité, puisque les fleurs ne seront cueillies que 24 heures avant d'arriver chez vous, contre environ 10 jours en moyenne pour les fleurs importées.</p>
                    <p><a class="box" href="{{path('producer')}}">Tous nos producteurs</a></p>
                </article>
            </section>
        </section>#}


        <section id="sectionhome5">
            <section class="contenuindex">
                <div>
                    <article>
                        <img src="/web/img/photo4.png" alt="">
                    </article>
                    <article>
                            <h2>A la une</h2>
                            <div class="trait"></div>
                            <h3>Une journée avec Anthony Charpal sur son exploitation de fleurs à Feucherolles</h3>
                            <p class="infos">Sur le calendrier, le printemps est arrivé depuis plusieurs jours. Dans nos jardins, le temps est à nouveau à la douceur. Profitons des conseils d'Anthony, notre horticulteur...</p>
                            <p><a id="p1" class="box" href="">Lire l'article</a></p>
                    </article>
                </div>
            </section>
        </section>


        <section id="sectionhome6">
            <section class="contenuindex">
                <h2>On parle des Fleurs d'Ici</h2>
                <div class="traitprofile"></div>
                <article>
                    <a href="https://goo.gl/y2Ajm8" target="blank"><img src="/web/img/presse/logo_we_demain_2.png" alt="icone presse we demain"></a>
                    
                    <a href="https://goo.gl/oT1M3o" target="blank"><img src="/web/img/presse/social_lab_2.jpg" alt="icone presse social lab"></a>
                    
                    <a href="https://goo.gl/omBrPX" target="blank"><img src="/web/img/presse/grazia_2.jpg" alt="icone presse Grazia"></a>

                    <a href="https://goo.gl/sH4jZB" target="blank"><img src="/web/img/presse/huffpost_2.png" alt="icone presse huffpost"></a>

                    <a href="https://goo.gl/iB3uvc" target="blank"><img src="/web/img/presse/rtl_2.png" alt="icone presse rtl"></a>

                    <a href="https://goo.gl/N5yeJf" target="blank"><img src="/web/img/presse/logo_elle.png" alt="icone presse Elle"></a>
                    
                    <a href="https://goo.gl/yKkLfX" target="blank"><img src="/web/img/presse/goodplanet.png" alt="icone presse fondation good planet"></a>
                    
                    <a href="https://goo.gl/yKkLfX" target="blank"><img src="/web/img/presse/david_jeannerot.jpg" alt="icone presse david jeannerot"></a>
                    
                    <a href="https://goo.gl/AZqxH4" target="blank"><img src="/web/img/presse/france_interr.png" alt="icone presse emission france inter" id="france_inter"></a>
                    {# PAS DE LIENS ACTIFS#}
                    {#<a href="https://goo.gl/yKkLfX" target="blank"><img src="/web/img/le_monde.png" alt="icone presse le monde"></a>
                    
                    <a href="https://goo.gl/N5yeJf" target="blank"><img src="/web/img/G&R.png" alt="icone presse Gustave et Rosalie"></a>#}
                    
                </article>
            </section>
        </section>
    </section>
    <section id="sectionhome7">        
        <section class="contenuindex" >
            <h2>Suivez-nous !</h2>
            <div class="traitprofile"></div>
            
            <article id="sociallink">
                <a href="https://goo.gl/Hqc6wL" target="blank"><i class="fa fa-facebook-official fa-2x" aria-hidden="true" target="blank"></i></a>
                <a href="https://goo.gl/yi2fNx" target="blank"><i class="fa fa-instagram  fa-2x" aria-hidden="true"></i></a>
                <a href="https://goo.gl/dhWckr" target="blank"><i class="fa fa-twitter  fa-2x" aria-hidden="true"></i></a>
            </article>    
            
            {# FLUX INSTAGRAM #}
            <div id="instafeed">
                <iframe src="https://snapwidget.com/embed/417032" class="snapwidget-widget" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:100%; "></iframe>
            </div>
            
            {# FLUX TWITTER #}
            <article class="flux">
               <a class="twitter-timeline" data-lang="fr" data-width="700" data-height="400" data-dnt="true" data-theme="dark" data-link-color="#E81C4F" href="https://twitter.com/fleursdici">Tweets by fleursdici</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
            </article>
            
            {# FLUX FACEBOOK #}
            <article class="flux">
               <iframe id="facebook" src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Flesfleursdici%2F&tabs=timeline&width=700&height=400&small_header=true&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="700" height="400" style="border:none; overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
            </article>

        </section>
    </section>
</section>

{% endblock %}

{% block javascript %}
{{ parent() }}
<link rel="javascript" href="{{asset('js/scriptindex.js')}}">

<script src="https://snapwidget.com/js/snapwidget.js"></script>

{{ parent() }}
<link rel="javascript" href="{{asset('js/scriptlayout.js')}}">

{% endblock %}


silex-skeleton/templates/login.html.twig
{%extends 'layout.html.twig' %}{% block content %}        <link rel="stylesheet" href="{{ asset('css/login2.css') }}" type="text/css">   <section id="mainconnect">    <h2 class="connecttitle">Connexion</h2>        <section class="contenuconnect" >            <section id="sectionconnect">                <form method="post" action="" id="formconnect">                    <article>                        <div class="inputcontainer">                            <label for="email"> Email : </label>                            <input type="text" name="email" value="">                        </div>                    </article>                    <article>                        <div class="inputcontainer">                            <label for="password"> Mot de passe : </label>                            <input type="password" name="password">                        </div>                    </article>                    <article>                        <div class="inputcontainer">                            <input type="submit" value="Envoyer">                        </div>                    </article>                </form>                <p>Vous n'avez pas encore de compte ? <a href="{{path('register')}}">Créez-en un !</a></p>                <p>Vous avez oublié votre mot de passe ? <a href="{{path('password')}}">Récupérez-le !</a> </p>            </section>             </section>    </section> {% endblock %}

silex-skeleton/templates/ourproject.html.twig
{% extends "layout.html.twig" %}

{% block content %}

<link rel="stylesheet" href="{{ asset('css/ourproject2.css') }}" type="text/css"> 

<h2 class="ourprojecttitle">Notre projet</h2>

    <section id="mainourproject1"> 
        
        <section class="contenuourproject">

            <section class="sectionourproject">

                <p class="descriptionourproject">Les Fleurs d'Ici c'est la première marque de fleurs coupées qui permet de contribuer à la protection de la nature et des emplois en France.
Des fleurs locales et de saison, comme si vous veniez de les cueillir au jardin.</p>
            
            </section>

        </section>

    </section>
    
<h2 class="ourprojecttitle">Comment ça marche ?</h3>

    <section id="mainourproject2"> 
        
        <section class="contenuourproject">
            
            <section id="sectionourproject2">
                <i class="fa fa-heart" aria-hidden="true"></i>
                <article class="howproject">
                    <h4 id="titleprojet">Recevez les plus belles fleurs</h4>
                    <p>Toute l'année recevez les plus belles fleurs de saison de France et de Navarre.</p>
                </article>
            </section>

            <section id="sectionourproject3">
                <i class="fa fa-handshake-o" aria-hidden="true"></i>
                <article class="howproject">
                    <h4 id="titleprojet2">Circuit-Court</h4>
                    <p>Nous privilégions le circuit court car nous pensons que les productions françaises sont de qualitées et qu'elles valent le coup d'être diffusées.</p>
                </article>
            </section>

            <section id="sectionourproject4">
                <i class="fa fa-telegram" aria-hidden="true"></i>
                <article class="howproject">
                    <h4 id="titleprojet3">Une ou deux fois par mois</h4>
                    <p>Livrées à domicile ou à récupérer en point-relais. Choisissez votre fréquence adéquate et la livraison qui vous facilite la vie.</p>
                </article>
            </section>
    
        </section>
    </section>


<h2 class="ourprojecttitle">Notre identité</h2>

    <section id="mainourproject3"> 

        <section class="contenuourproject">

            <section class="sectionourproject">

                <p class="descriptionourproject">Le marché des fleurs coupées est une industrie mondialisée.

Aujourd’hui, 85% des fleurs vendues en France viennent de l’étranger, de Hollande bien sûr, mais de plus en plus, du Kenya, d’Équateur ou de Colombie.

En remettant la saisonnalité et la proximité au cœur de la dynamique de consommation, Fleurs d’Ici permet aux petits producteurs horticoles de vendre leurs fleurs au juste prix, en économisant sur le circuit de distribution, et aux consommateurs d’avoir des produits de meilleure qualité, tout en s’inscrivant dans une démarche de développement durable.</p>

                <img src="https://res.cloudinary.com/hrscywv4p/image/upload/c_limit,fl_lossy,h_1440,w_720,f_auto,q_auto/v1/1135015/4de25634-5c76-4b3b-a4cb-e073c8eeaa1a_qzbbtj.png" alt="">
            </section>

        </section>

    </section>

{% endblock %}

{% block stylesheet %} 
 
    {{parent()}} 
 

 {% endblock %} 

silex-skeleton/templates/panier.html.twig
{% extends "layout.html.twig" %}

{% block content %}

    <link rel="stylesheet" href="{{ asset('css/panier.css') }}" type="text/css">


    <section id="panier">

            <section id="mainpanier">

                    <section class="contenupanier" >

                            <section id="sectionpanier1">
                                <h2 class="paniertitle"> {%if duration is not null %}<i class="fa fa-gift" aria-hidden="true"></i>{%else%}<i class="fa fa-shopping-basket" aria-hidden="true"></i>{%endif%}</h2>
                                {% if product is defined %}
                                    {%if duration is not null %}          
                                    <p class="paniermessage">Offrez une carte cadeau imprimable, valable un an à partir de sa date d'activation et faites plaisir à un(e) ami(e) ! </p>
                                    {% else %}
                                    <p class="paniermessage">Bravo et merci, vous avez choisi de fleurir votre maison avec des fleurs locales et de saison. Il ne vous reste plus qu'à valider votre commande.</p>
                                    {%endif %}
                                    <section id="photoproduitpanier">

                                        <h3 class="produitpanier"><span>{{ product.productName }}</span></h3>

                                        <img src="{{ asset('/web/img/' ~ product.photo) }}" alt="photo du bouquet {{product.productName}}">

                                    </section>

                                    <section id="prixpanier">
                                        <p><b>Prix : {%if duration is not null %}{{ product.price * duration}}{%else%}{{ product.price}}{%endif%}€</b>{%if duration is not null%} pour une durée de {{duration}} mois.{%endif%}</p>
                                        <b>Frais de port :</b> {{shipping.shippingfees}} € {%if duration is not null %} par mois{%endif%} pour une livraison {%if shipping.mode == 'point relais'%}en point fleurs{% elseif shipping.mode == 'domicile'%}à domicile{%endif%}.
                                        <p><b>Description :</b> {{ product.description }}</p>
                                        
                                        
                                        {% if duration is null %}
                                            {% if pointrelais is null %}
                                                {% if user_manager.isUserConnected %}
                                                    <p><b>Vérification de votre adresse :</b></p>
                                                    <p>{{user_manager.firstname}} {{user_manager.firstname}}, {{user_manager.address}}, {{user_manager.zipcode}} {{user_manager.city}}</p>
                                                {% else %}
                                                    <p<a href="{{path('login')}}">Connectez-vous pour vérifier votre adresse de livraison.</a></p>
                                                {% endif %}
                                            {% else %}
                                                <p><b>Le point relais que vous avez choisi est :</b></p>
                                                <p>{{pointrelais.namepul}} - {{pointrelais.addresspul}}, {{pointrelais.zipcodepul}} {{pointrelais.citypul}}</p>
                                            {% endif %}
                                        {%else%}
                                            <p><b>Vérification de votre email :</b>  {{user_manager.email}} <br>
                                            Vous recevrez la carte cadeau par email à la fin de votre achat.</p>
                                        {%endif%}
                                        
                                    </section>

                                    <section id="totalpanier">
                                        <div><h4>Total de votre commande :</h4></div>
                                        <div>{%if duration is not null %}{{(product.price + shipping.shippingfees) *duration}}{%else%}{{(product.price + shipping.shippingfees)}}{%endif%}€</div>
                                    </section>
                                    
                                    
                                    <section id="validationpanier">
                                   {% if user_manager.isUserConnected()%}
                                       
                                       <a href="
                                          {%if duration is not null %}
                                            {{path('paiement_charge')}}
                                          {% elseif abonnement is not null%}
                                              #
                                          {%else%}
                                              {{path('paiement_abonnement')}}
                                          {%endif%}">Valider
                                       </a> 
                                          
                                    {%else%}<a href="{{path('login')}}">Connectez-vous d'abord</a>{% endif %}
                                    
                                    </section>
                                {%else%}
                                    <p class="paniermessage" style="margin-bottom: 0">Votre panier de fleurs est vide !</p>
                                    <p style='text-align:center; font-size: 2rem;'>
                                    <a href="{{path ('abonnement')}}" style='text-align:center;'>Remplissez-le !</a>
                                    </p>
                                {%endif%}
                    </section>
                </section>
            </section>
{% endblock %}

{% block stylesheet %}
    {{parent()}}

 {% endblock %}

{% block javascript %}
    {{parent()}}
    <link rel="javascript" href="{{ asset('js/jquery.js') }}" type="text/js">
 {% endblock %}